# Generated by Django 5.0.7 on 2024-07-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_onepiececard_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onepiececard',
            name='name',
        ),
        migrations.AddField(
            model_name='onepiececard',
            name='art',
            field=models.IntegerField(default=-999),
        ),
        migrations.AddField(
            model_name='onepiececard',
            name='card_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='onepiececard',
            name='card_set',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='onepiececard',
            name='category',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='onepiececard',
            name='key',
            field=models.CharField(default='test', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onepiececard',
            name='rarity',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='onepiececard',
            name='trigger',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='onepiececard',
            name='card_id',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='onepiececard',
            name='color',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='onepiececard',
            name='type',
            field=models.JSONField(default=list),
        ),
    ]
