# Generated by Django 5.0.7 on 2024-07-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_onepiececard_name_onepiececard_art_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FusionWorldCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10, unique=True)),
                ('export', models.IntegerField(default=-999)),
                ('card_id', models.JSONField(default=list)),
                ('rarity', models.CharField(default='N/A', max_length=10)),
                ('category', models.CharField(default='N/A', max_length=50)),
                ('card_name', models.CharField(default='N/A', max_length=100)),
                ('cost', models.JSONField(default=dict)),
                ('power', models.IntegerField(default=-999)),
                ('counter', models.IntegerField(default=-999)),
                ('color', models.JSONField(default=list)),
                ('type', models.JSONField(default=list)),
                ('effect', models.TextField(default='N/A')),
                ('art', models.IntegerField(default=-999)),
                ('trigger', models.CharField(default='N/A', max_length=100)),
                ('card_set', models.CharField(default='N/A', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fusion_world_cards/')),
            ],
        ),
        migrations.DeleteModel(
            name='YuGiOhCard',
        ),
    ]
